services:
  backend:
    build: ./src
    ports:
      - "${HOST_APP_PORT}:${APP_PORT}"
    environment:
      - ConnectionStrings__DatabaseConnection=Server=mssql,1433;Database=master;User Id=sa; Password=${DB_PASSWORD};TrustServerCertificate=True
      - ASPNETCORE_URLS=http://0.0.0.0:${APP_PORT}
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "${HOST_DB_PORT}:1433"